---
- hosts: raspi_cluster
  remote_user: "{{ raspi_user }}"
  tasks:
    - import_role:
        name: secure_sshd
    - import_role:
        name: remove_default_user
    - import_role:
        name: apt_upgrade
    - import_role:
        name: install_basics
    - import_role:
        name: dotfiles
