---
- hosts: raspi_cluster
  remote_user: pi
  gather_facts: no
  become: yes
  vars:
    raspi_user_groups:
      - pi
      - adm
      - dialout
      - cdrom
      - sudo
      - audio
      - video
      - plugdev
      - games
      - users
      - input
      - netdev
      - gpio
      - i2c
      - spi
  tasks:
    - name: "Create new user named {{ raspi_user }}"
      user:
        name: "{{ raspi_user }}"
        groups: "{{ raspi_user_groups }}"
        append: yes
    - name: "Set ssh authorized key for user {{ raspi_user }}"
      authorized_key:
        user: "{{ raspi_user }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    - name: allow passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s' 
