---
- name: Get dotfiles
  git:
    repo: https://github.com/fsicardir/Dotfiles.git
    dest: "/home/{{ raspi_user }}/Dotfiles"
- name: Run config script
  shell: "/home/{{ raspi_user }}/Dotfiles/update_local_config.sh"
  args:
    chdir: "/home/{{ raspi_user }}/Dotfiles"
