---
- name: Get dotfiles
  git:
    repo: https://github.com/fsicardir/Dotfiles.git
    dest: ~/Dotfiles
  register: updated_dotfiles
- name: Run config script
  command: ~/Dotfiles/update_local_config.sh
  args:
    chdir: ~/Dotfiles
  when: updated_dotfiles.changed
  notify: Reboot host
