- name: Upgrade all packages to the latest version
  become: yes
  apt:
    name: "*"
    force_apt_get: yes
    update_cache: yes
    state: latest
- name: Remove useless packages from the cache
  become: yes
  apt:
    force_apt_get: yes
    autoclean: yes
- name: Remove dependencies that are no longer required
  become: yes
  apt:
    force_apt_get: yes
    autoremove: yes   
    state: latest
